import {
  createTheme,
  Stack,
  ThemeProvider,
  PaletteMode,
  Box,
} from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Add, Feed, Navbar, RightBar, SideBar } from "../components";

const Home: NextPage = () => {
  const [mode, setMode] = useState<PaletteMode>("light");

  const darkTheme = createTheme({
    palette: {
      mode: mode,
    },
  });

  return (
    <ThemeProvider theme={darkTheme}>
      <Box bgcolor="background.default" color="text.primary">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Stack direction="row" spacing={2} justifyContent="space-between">
          <SideBar mode={mode} setMode={setMode} />
          <Feed />
          <RightBar />
        </Stack>
        <Add />
      </Box>
    </ThemeProvider>
  );
};

export default Home;
